/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ClientsIdRouteImport } from './routes/clients/$id'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiNotesRouteImport } from './routes/api/notes'
import { Route as ApiInvitesRouteImport } from './routes/api/invites'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiClientsRouteImport } from './routes/api/clients'
import { Route as PortalProjectsIndexRouteImport } from './routes/portal/projects/index'
import { Route as PortalProjectsIdRouteImport } from './routes/portal/projects/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesRoute = ApiInvitesRouteImport.update({
  id: '/api/invites',
  path: '/api/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientsRoute = ApiClientsRouteImport.update({
  id: '/api/clients',
  path: '/api/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectsIndexRoute = PortalProjectsIndexRouteImport.update({
  id: '/portal/projects/',
  path: '/portal/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectsIdRoute = PortalProjectsIdRouteImport.update({
  id: '/portal/projects/$id',
  path: '/portal/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/clients': typeof ApiClientsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invites': typeof ApiInvitesRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/clients': typeof ApiClientsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invites': typeof ApiInvitesRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients': typeof ClientsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/projects': typeof PortalProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/api/clients': typeof ApiClientsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/invites': typeof ApiInvitesRoute
  '/api/notes': typeof ApiNotesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/search': typeof ApiSearchRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
  '/portal/projects/': typeof PortalProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/api/clients'
    | '/api/health'
    | '/api/invites'
    | '/api/notes'
    | '/api/projects'
    | '/api/search'
    | '/clients/$id'
    | '/clients/'
    | '/portal/'
    | '/projects/'
    | '/portal/projects/$id'
    | '/portal/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/api/clients'
    | '/api/health'
    | '/api/invites'
    | '/api/notes'
    | '/api/projects'
    | '/api/search'
    | '/clients/$id'
    | '/clients'
    | '/portal'
    | '/projects'
    | '/portal/projects/$id'
    | '/portal/projects'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/api/clients'
    | '/api/health'
    | '/api/invites'
    | '/api/notes'
    | '/api/projects'
    | '/api/search'
    | '/clients/$id'
    | '/clients/'
    | '/portal/'
    | '/projects/'
    | '/portal/projects/$id'
    | '/portal/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ApiClientsRoute: typeof ApiClientsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInvitesRoute: typeof ApiInvitesRoute
  ApiNotesRoute: typeof ApiNotesRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  PortalProjectsIdRoute: typeof PortalProjectsIdRoute
  PortalProjectsIndexRoute: typeof PortalProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites': {
      id: '/api/invites'
      path: '/api/invites'
      fullPath: '/api/invites'
      preLoaderRoute: typeof ApiInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clients': {
      id: '/api/clients'
      path: '/api/clients'
      fullPath: '/api/clients'
      preLoaderRoute: typeof ApiClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/projects/': {
      id: '/portal/projects/'
      path: '/portal/projects'
      fullPath: '/portal/projects/'
      preLoaderRoute: typeof PortalProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/projects/$id': {
      id: '/portal/projects/$id'
      path: '/portal/projects/$id'
      fullPath: '/portal/projects/$id'
      preLoaderRoute: typeof PortalProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ApiClientsRoute: ApiClientsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInvitesRoute: ApiInvitesRoute,
  ApiNotesRoute: ApiNotesRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ClientsIdRoute: ClientsIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  PortalProjectsIdRoute: PortalProjectsIdRoute,
  PortalProjectsIndexRoute: PortalProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
